parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
            default_connection:     achat_centrale
            connections:
                centrale_produits:
                    driver_class:   Lsw\DoctrinePdoDblib\Doctrine\DBAL\Driver\PDODblib\Driver
                    host:           "185.29.149.144"
                    user:           "AC_JBAGOSTIN"
                    password:       "35H7Hjvy"
                    dbname:         "CENTRALE_PRODUITS_JB"
                    charset:  UTF-8
                    options:
                        ansi_nulls: on
                        ansi_warnings: on
                        20: false
                centrale_funecap:
                     driver_class:   Lsw\DoctrinePdoDblib\Doctrine\DBAL\Driver\PDODblib\Driver
                     host:           "185.29.149.144"
                     user:           "AC_JBAGOSTIN"
                     password:       "35H7Hjvy"
                     dbname:         "CENTRALE_FUNECAP"
                     charset:  UTF-8
                     options:
                         ansi_nulls: on
                         ansi_warnings: on
                         20: false
                achat_centrale:
                    driver_class:   Lsw\DoctrinePdoDblib\Doctrine\DBAL\Driver\PDODblib\Driver
                    host:         "185.29.149.144"
                    user:         "AC_JBAGOSTIN"
                    password:     "35H7Hjvy"
                    dbname:       "CENTRALE_ACHAT"
                    charset:  UTF-8
                    options:
                        ansi_nulls: on
                        ansi_warnings: on
                        20: false
                roc_eclerc:
                    driver_class:   Lsw\DoctrinePdoDblib\Doctrine\DBAL\Driver\PDODblib\Driver
                    host:         "185.29.149.144"
                    user:         "AC_JBAGOSTIN"
                    password:     "35H7Hjvy"
                    dbname:       "CENTRALE_ROC_ECLERC"
                    charset:  UTF-8
                    options:
                         ansi_nulls: on
                         ansi_warnings: on
                         20: false
                centrale_gccp:
                    driver_class:   Lsw\DoctrinePdoDblib\Doctrine\DBAL\Driver\PDODblib\Driver
                    host:         "185.29.149.144"
                    user:         "AC_JBAGOSTIN"
                    password:     "35H7Hjvy"
                    dbname:       "CENTRALE_GCCP"
                    charset:  UTF-8
                    options:
                        ansi_nulls: on
                        ansi_warnings: on
                        20: false
                centrale_pascal_leclerc:
                    driver_class:   Lsw\DoctrinePdoDblib\Doctrine\DBAL\Driver\PDODblib\Driver
                    host:         "185.29.149.144"
                    user:         "AC_JBAGOSTIN"
                    password:     "35H7Hjvy"
                    dbname:       "CENTRALE_PFPL"
                    charset:  UTF-8
                    options:
                        ansi_nulls: on
                        ansi_warnings: on
                        20: false
                ac_produits:
                    driver_class:   Lsw\DoctrinePdoDblib\Doctrine\DBAL\Driver\PDODblib\Driver
                    host:         "185.29.149.144"
                    user:         "AC_JBAGOSTIN"
                    password:     "35H7Hjvy"
                    dbname:       "CENTRALE_PRODUITS"
                    charset:  UTF-8
                    options:
                        ansi_nulls: on
                        ansi_warnings: on
                        20: false
    orm:
            auto_generate_proxy_classes: "%kernel.debug%"
            default_entity_manager:  achat_centrale
            entity_managers:
                centrale_produits:
                    connection: centrale_produits
                centrale_funecap:
                    connection: centrale_funecap
                achat_centrale:
                    connection: achat_centrale
                roc_eclerc:
                    connection: roc_eclerc
                centrale_gccp:
                    connection: centrale_gccp
                centrale_pascal_leclerc:
                    connection: centrale_pascal_leclerc
                ac_produits:
                    connection: ac_produits

